// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, email, phone, hashed_password)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, phone, email, hashed_password, status, created_at, updated_at
`

type CreateUserParams struct {
	ID             string      `json:"id"`
	Username       string      `json:"username"`
	Email          pgtype.Text `json:"email"`
	Phone          pgtype.Text `json:"phone"`
	HashedPassword string      `json:"hashed_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Phone,
		arg.HashedPassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Phone,
		&i.Email,
		&i.HashedPassword,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
