// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateBlock(ctx context.Context, arg CreateBlockParams) error
	CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error)
	CreateContactRequest(ctx context.Context, arg CreateContactRequestParams) (ContactRequest, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBlock(ctx context.Context, arg DeleteBlockParams) error
	DeleteContact(ctx context.Context, arg DeleteContactParams) error
	FindUserByIdentifier(ctx context.Context, arg FindUserByIdentifierParams) (User, error)
	GetContactRequest(ctx context.Context, id string) (ContactRequest, error)
	IsBlocked(ctx context.Context, arg IsBlockedParams) (bool, error)
	ListContacts(ctx context.Context, arg ListContactsParams) ([]Contact, error)
	UpdateContactRequestState(ctx context.Context, arg UpdateContactRequestStateParams) error
}

var _ Querier = (*Queries)(nil)
